name: CI - FastAPI Build Check

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    name: FastAPI Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install Dependencies
        run: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt || pip install fastapi uvicorn

      - name: FastAPI Syntax Check
        run: |
            echo "✅ Syntax 체크용 dummy run"
            python -m py_compile main.py
